[build]
  command = "pnpm run build"
  publish = ".next"

[dev]
  command = "pnpm run dev"

[build.environment]
  NODE_VERSION = "18"

# Uncomment below if you need to handle client-side routing
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
